from typing import Protocol
from uuid import UUID

from app.ingestion.domain.document import Document


class DocumentRepoProto(Protocol):
    async def save(self, document: Document) -> None: ...

    async def get_by_uuid(self, uuid: str) -> Document | None: ...

    async def get_by_batch_id(self, batch_id: UUID) -> list[Document]: ...

    async def list_by_repository_sync_id(self, sync_id: UUID) -> list[Document]: ...

    async def get_by_repository_and_source_id(
        self, repository_id: UUID, source_id: str
    ) -> Document | None: ...

    async def list_by_repository_id(self, repository_id: UUID) -> list[Document]: ...
    async def list_all(self) -> list[Document]: ...

    async def get_by_hash(self, content_hash: str) -> Document | None: ...

    async def delete_by_uuids(self, uuids: list[UUID]) -> None: ...
