name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: Build and Run Checks
        run: |
          docker compose build app
          make check

      - name: Run Tests (excluding e2e)
        run: |
          make test
